mystie/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("register/",views.RegisterView.as_view(),name='register'),
]

mystie/mystie/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include("product.urls", namespace="product")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('accounts/',include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

mystie/product/urls.py
from django.urls import path

from . import views

app_name = "product"

urlpatterns = [
    path('',views.product_list,name="product_list"),
    path('<int:id>',views.product_detail, name ="product_detail"),
]

mystie/accounts/models.py
from django.db import models

# Create your models here.

mystie/product/models.py
from distutils.command.upload import upload
from urllib import request
from django.db import models
from django.forms import CharField, DateTimeField, HiddenInput
from django.utils import timezone

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d/",blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    number = models.IntegerField(default=1)
    description = models.TextField(default="خالی",max_length=100)
    
    
    @property
    def dollar_amount(self):
        return "$%s" % self.price if self.price else ""
    
    @property
    def availability(self):
        return "%s" % "موجود" if self.available else "ناموجود"
   
    def __str__(self):
        return self.name
    
    
class comments(models.Model):
    product = models.ForeignKey(Product,related_name="comments1", on_delete=models.CASCADE )
    comment = models.TextField()
    writer = "ali"
    
    def __str__(self):
        return str(self.writer)+""+str(self.id)

mystie/product/forms.py
from django import forms



class Buy(forms.Form):

    def __init__(self,*args,**kwargs):
        quantity_m = kwargs.pop("quantity_m")
        PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range (1,quantity_m+1)]
        super(Buy, self).__init__(*args,**kwargs)
        self.fields['quantity'] = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)

mystie/accounts/views.py
from django.shortcuts import render

from django.views import generic

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/register.html"
    
    

mystie/product/views.py
from django.shortcuts import get_object_or_404, render
from .models import Product , comments
# Create your views here.
from .forms import Buy

def product_list(request):
    products = Product.objects.all()
    
    context = {
        "products" : list(products),
    }
    return render(request,"product/product_list.html",context)

def product_detail(request,id):
    
    selected_product = get_object_or_404(Product,id=id)
    
    comments2 = selected_product.comments1
    
    if selected_product.available :
        buy_form = Buy(quantity_m = selected_product.number)
    else :
        buy_form = False
    
    context = {
        "s_product" : selected_product ,
        "buy_form1" : buy_form ,
        "comments3" : comments2
    }
    return render(request,"product/product_detail.html",context)


mystie/templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>



        

    </head>

    <body style=' height: 100% ; width: 100% ; background-color:aqua'   >

        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="http://localhost:8000/product/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                    
                      
                  {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link ">Hello {{user.username}}</a></li>
                    <li class="nav-item"><a class="nav-link " href="{% url 'logout'%}">LogOut</a></li>
                  {%else%}
                    <li class="nav-item"><a class="nav-link " href="{% url 'login'%}">Login</a></li>     
                  {% endif %}
                        
                  


                  
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>


          

        <div style='background-image: url("{% static "images/the_lego_batman_movie_4k-3840x2160.jpg"%}"); height: 1000px;
        width: 100%; ; background-position: center ; background-repeat: no-repeat;background-size: cover;'>
            
            {% block content %}
                      
                      
            {% endblock content %}
            
        </div>
        
        
      
    
    </body>
</html>

mystie/templates/product/product_detail.html
{% extends 'base.html' %}

{% block content %}

        <div style=" width: 50% ; position: relative ; left: 130px; top:150px ; display: table; background: #EECDA3;  /* fallback for old browsers */
                background: -webkit-linear-gradient(to right, #EF629F, #EECDA3);  /* Chrome 10-25, Safari 5.1-6 */
                background: linear-gradient(to right, #EF629F, #EECDA3); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                ; padding : 10px ;">
                    {% comment %} <div style="border: 2px solid red; border-radius: 5px; width:70%" class="mx-auto" >
                      <img src="{{s_product.image.url}}" class="card-img-top" alt="..." width="auto" height="auto" >
                    </div> {% endcomment %}
                    <div class="card" style="width: 18rem; float: left;background: #e96443;  /* fallback for old browsers */
                    background: -webkit-linear-gradient(to right, #904e95, #e96443);  /* Chrome 10-25, Safari 5.1-6 */
                    background: linear-gradient(to right, #904e95, #e96443); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                    ">
                      
                      <img src="{{s_product.image.url}}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h1> {{s_product.name}}</h1>
                        <h2> {{s_product.dollar_amount}} $</h2>
                        <h3> {{s_product.availability}}</h3>
                      </div>

                    </div>

                    <div style=" width: 50% ; background-color:white ; padding : 10px ; float: left; margin: 0px 10px 0px 10px">
                      
                      {% if buy_form1 %}
                          <form action="">
                            {{buy_form1.as_p}}
                            {% csrf_token %}
                            <input type="submit" value="Buy it">
                          </form>
                      {% else %}
                          <a href="">اطلاع بده</a>
                      {% endif %}

                      <p align=right> {{s_product.updated}} :تاریخ آخرین بروزرسانی</p>
                      <p align=right> {{s_product.created}} :تاریخی</p>
                      <p>{{s_product.comments1.all}}</p>
                      <p>{{s_product.description}}</p>

                      <ul>
                        
                        {% for choice in s_product.comments_set.all %}
                          <p>hi</p>
                          <li>{{ choice.comment }}</li>
                        {% endfor %}
                        </ul>
                    </div >
                  
                    
        </div>  

{% endblock content %}

mystie/templates/product/product_list.html
{% extends 'base.html' %}

{% block content %}

    <div style=" width: 50% ; position: relative ; left: 130px; top:150px ">
      {% comment %} <ul class="list-group">
          <li class="list-group-item active" aria-current="true">My products</li>
          {% for product in products  %}
              <li class="list-group-item">
                <a href="{% url 'product:product_detail' product.id %}">{{product.name}}</a>
              </li>
          {% endfor %}
      </ul>  {% endcomment %}
      <div class="row row-cols-1 row-cols-md-3 g-4">
        

        {% for product in products  %}
        <a href="{% url 'product:product_detail' product.id %}">
          <div class="col mx-4">
            <div class="card">
              <img src="{{product.image.url}}" class="card-img-top" alt="...">
              
              <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">{{product.dollar_amount}}</p>
              </div>
            </div>
          </div>
        </a>
            
        {% endfor %}



      </div>
      
    </div> 

{% endblock content %}